"""
AgentState — Shared state schema for the Ultimate Secure Local OS Executive Agent.

Every node in the LangGraph workflow reads from and writes to this TypedDict.
The `messages` field uses LangGraph's built-in `add_messages` reducer so that
multiple nodes can safely append messages without overwriting each other.
"""

from typing import Annotated
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    # ── Conversation history ─────────────────────────────────────────────────
    # Uses add_messages reducer: new messages are appended, not replaced.
    messages: Annotated[list[BaseMessage], add_messages]

    # ── Execution plan ───────────────────────────────────────────────────────
    # Ordered list of steps generated by the PlannerNode.
    plan: list[str]

    # ── Progress tracking ────────────────────────────────────────────────────
    # Steps acknowledged as done by the ReviewerNode.
    completed_steps: list[str]

    # ── Working directory ────────────────────────────────────────────────────
    # Absolute path on the Windows machine the agent is operating in.
    workspace: str

    # ── Error log ────────────────────────────────────────────────────────────
    # Accumulates stderr / exception snippets for the ReviewerNode to analyse.
    error_logs: list[str]

    # ── Safety counter ───────────────────────────────────────────────────────
    # Incremented by WorkerNode each cycle. Graph halts at MAX_ITERATIONS.
    iteration_count: int

    # ── Human-in-the-Loop flags ──────────────────────────────────────────────
    # Set to True by WorkerNode when a destructive or CAPTCHA event is detected.
    # Cleared back to False after the user responds via Chainlit UI.
    requires_human_approval: bool

    # Holds the exact command / context string waiting for human review.
    pending_command: str
