"""
AgentState — Shared state schema for the Ultimate Secure Local OS Executive Agent.

Every node in the LangGraph workflow reads from and writes to this TypedDict.
The `messages` field uses a custom reducer that appends messages while enforcing
a maximum history limit (default 300) to prevent memory exhaustion during long sessions.
"""

from typing import Annotated
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage


def _add_messages_with_limit(left: list[BaseMessage], right: list[BaseMessage] | BaseMessage, max_messages: int = 300) -> list[BaseMessage]:
    """
    Custom reducer for messages that enforces a maximum limit.

    Keeps the oldest summary messages and most recent messages to stay under max_messages.
    Strategy: Keep first 50 (summaries) + last 250 (recent context).
    """
    # Normalize right to list
    if isinstance(right, BaseMessage):
        right = [right]
    else:
        right = list(right)

    combined = list(left) + list(right)

    if len(combined) <= max_messages:
        return combined

    # Keep first 50 (summaries) and last 250 (recent)
    keep_old = 50
    keep_recent = 250

    if len(combined) > max_messages:
        combined = combined[:keep_old] + combined[-(max_messages - keep_old):]

    return combined


def _add_messages(left: list[BaseMessage], right: list[BaseMessage] | BaseMessage) -> list[BaseMessage]:
    """Wrapper for the default add_messages behavior with limit enforcement."""
    return _add_messages_with_limit(left, right, max_messages=300)


class AgentState(TypedDict):
    # ── Conversation history ─────────────────────────────────────────────────
    # Uses custom _add_messages reducer: appends messages while enforcing max 300 limit.
    messages: Annotated[list[BaseMessage], _add_messages]

    # ── Execution plan ───────────────────────────────────────────────────────
    # Ordered list of steps generated by the PlannerNode.
    plan: list[str]

    # ── Progress tracking ────────────────────────────────────────────────────
    # Steps acknowledged as done by the ReviewerNode.
    completed_steps: list[str]

    # ── Working directory ────────────────────────────────────────────────────
    # Absolute path on the Windows machine the agent is operating in.
    workspace: str

    # ── Error log ────────────────────────────────────────────────────────────
    # Accumulates stderr / exception snippets for the ReviewerNode to analyse.
    error_logs: list[str]

    # ── Safety counter ───────────────────────────────────────────────────────
    # Incremented by WorkerNode each cycle. Graph halts at MAX_ITERATIONS.
    iteration_count: int

    # ── Human-in-the-Loop flags ──────────────────────────────────────────────
    # Set to True by WorkerNode when a destructive or CAPTCHA event is detected.
    # Cleared back to False after the user responds via Chainlit UI.
    requires_human_approval: bool

    # Holds the exact command / context string waiting for human review.
    pending_command: str

    # ── Deduplication tracking ───────────────────────────────────────────────
    # Prevents duplicate tool calls and identical messages
    tool_call_history: list[dict]  # Last 20 tool invocations with name, args, timestamp
    last_tool_name: str  # Name of the most recent tool called
    last_tool_args: dict  # Arguments of the most recent tool call
    last_message_content: str  # Hash of the last AI message to prevent exact duplicates
    task_id: str  # Unique ID for current task (changes when task is restarted)
